```{r}
library(lubridate)
library(survival)
library(survminer)
library(ggplot2)
library(dplyr)
library(timereg)
```

```{r}
# Load the AaveV2 Ethereum transaction data and filter out transactions after October 1, 2022 since 
# this is the data we used in the original paper

transactions <- read_rds("/data/IDEA_DeFi_Research/Data/Lending_Protocols/Aave/V2/Mainnet/transactions.rds")
coinTypes <- read_csv("/data/IDEA_DeFi_Research/Data/Coin_Info/stablecoins.csv")
# Run the files to make the functions that create the survival data:
source("./Survival_Data_Creation/createSurvData.R")

tFinal <- as_datetime(ymd("2022-10-01"))

transactions <- transactions %>%
  filter(timestamp <= tFinal) %>%
  mutate(coinType = case_when(reserve %in% coinTypes$symbol ~ "Stable",
                              TRUE ~ "Non-Stable"))

## Helper functions
not_all_na <- function(x) any(!is.na(x))
`%notin%` <- Negate(`%in%`)
select <- dplyr::select
mutate <- dplyr::mutate
rename <- dplyr::rename

```

```{r}
# For this notebook, we just need to recreate a few of our analyses with competing risks. 

# First, lets recreate figure 2, which is the figure showing the likelihood of each event type being the next event after a deposit.

indexEventSet <- c("deposit")
outcomeEventSet <- c("withdraw", "borrow", "repay", "liquidation")
subjects <- c("user")
indexCovariates <- c()
outcomeCovariates <- c("type")
observationPeriod <- c(0, tFinal)

depositToAll <- createSurvData(indexEventSet, 
                               outcomeEventSet, 
                               transactions, 
                               subjects, 
                               observationPeriod, 
                               indexCovariates, 
                               outcomeCovariates)

depositToAll <- depositToAll %>%
  mutate(endpoint = as_factor(case_when(status == 0 ~ "censor",
                           TRUE ~ type))) %>%
  filter(timeDiff != 0) %>%
  mutate(istate = "deposit") %>%
  dplyr::select(id = indexID,
         time = timeDiff,
         endpoint,
         istate)

smallSet <- depositToAll %>%
  slice_sample(prop = 0.05)


fit <- survfit(formula = Surv(time/86400, endpoint) ~ 1, data = smallSet, id=id, istate=istate)

plot(fit, col=1:4, lty=1:5, lwd=2, ylab="Probability in state")
```

```{r}
indexEventSet <- c("borrow")
outcomeEventSet <- c("repay", "liquidation")
transactions <- transactions %>%
  mutate(reserve = case_when(type == "liquidation" ~ principalReserve,
                             TRUE ~ reserve)) %>%
  mutate()
subjects <- c("user",
              "reserve")
indexCovariates <- c("coinType")
outcomeCovariates <- c("type")
observationPeriod <- c(0, tFinal)
  
borrowToOutcome <- createSurvData(indexEventSet, outcomeEventSet, transactions, subjects, observationPeriod, indexCovariates, outcomeCovariates)


borrowToOutcome <- borrowToOutcome %>%
  mutate(endpoint = as_factor(case_when(status == 0 ~ "censor",
                           TRUE ~ type))) %>%
  filter(timeDiff != 0) %>%
  mutate(istate = "borrow") %>%
  select(id = indexID,
         time = timeDiff,
         endpoint,
         istate,
         coinType)

smallSet <- borrowToOutcome %>%
  slice_sample(prop = 0.05)


fit <- survfit(formula = Surv(time/86400, endpoint) ~ 1, data = smallSet, id=id, istate=istate)
plot(fit, col=1:4, lty=1:5, lwd=2, ylab="Probability in state")
```

## Sample Code for Comp.Risk function:

```{r}
data(bmt)
clust <- rep(1:204,each=2)
addclust<-comp.risk(Event(time,cause)~platelet+age+tcell+survival::cluster(clust),
                    data=bmt,
                    cause=1,
                    resample.iid=1,
                    n.sim=100,
                    model="additive")
###
addclust<-comp.risk(Event(time,cause)~+1+survival::cluster(clust),
                    data=bmt,
                    cause=1,
                    resample.iid=1,
                    n.sim=100,
                    model="additive")

pad <- predict(addclust,X=1)
plot(pad)
```
```{r}
smallSet <- smallSet %>%
  mutate(cause = as.numeric(endpoint)) %>%
  drop_na()
test <- comp.risk(Event(time/86400, cause, cens.code=1)~coinType,
                  data=smallSet,
                  cause=3,
                    resample.iid=1,
                    n.sim=100,
                    model="prop")
summary(test)
par(mfrow=c(2,4))
plot(test)
```

```{r}
add<-comp.risk(Event(time,cause)~platelet+age+tcell,
               data=bmt,
               cause=1,
               resample.iid=1,
               n.sim=100,
               model="additive")
summary(add)
par(mfrow=c(2,4))
plot(add)
### plot(add,score=1) ### to plot score functions for test
```

```{r}
ndata<-data.frame(platelet=c(1,0,0),age=c(0,1,0),tcell=c(0,0,1))
par(mfrow=c(2,3))
out<-predict(add,ndata,uniform=1,n.sim=100)
par(mfrow=c(2,2))
plot(out,multiple=0,uniform=1,col=1:3,lty=1,se=1)
```

```{r}
## fits additive model with some constant effects
add.sem<-comp.risk(Event(time,cause)~const(platelet)+const(age)+const(tcell),
                   data=bmt,
                   cause=1,
                   resample.iid=1,
                   n.sim=100,
                   model="additive")
summary(add.sem)
out<-predict(add.sem,ndata,uniform=1,n.sim=100)
par(mfrow=c(2,2))
plot(out,multiple=0,uniform=1,col=1:3,lty=1,se=0)
```

```{r}
## Fine & Gray model
fg<-comp.risk(Event(time,cause)~const(platelet)+const(age)+const(tcell),
              data=bmt,
              cause=1,
              resample.iid=1,
              model="fg",
              n.sim=100)
summary(fg)
out<-predict(fg,ndata,uniform=1,n.sim=100)
par(mfrow=c(2,2))
plot(out,multiple=1,uniform=0,col=1:3,lty=1,se=0)
```

```{r}
## extended model with time-varying effects
fg.npar<-comp.risk(Event(time,cause)~platelet+age+const(tcell),
                   data=bmt,
                   cause=1,
                   resample.iid=1,
                   model="prop",
                   n.sim=100)
summary(fg.npar);
out<-predict(fg.npar,ndata,uniform=1,n.sim=100)
head(out$P1[,1:5]); head(out$se.P1[,1:5])
par(mfrow=c(2,2))
plot(out,multiple=1,uniform=0,col=1:3,lty=1,se=0)
```

```{r}
## Fine & Gray model with alternative parametrization for baseline
fg2<-comp.risk(Event(time,cause)~const(platelet)+const(age)+const(tcell),
               data=bmt,
               cause=1,
               resample.iid=1,
               model="prop",
               n.sim=100)
summary(fg2)
```

```{r}
#################################################################
## Delayed entry models,
#################################################################
nn <- nrow(bmt)
entrytime <- rbinom(nn,1,0.5)*(bmt$time*runif(nn))
bmt$entrytime <- entrytime
times <- seq(5,70,by=1)
bmtw <- prep.comp.risk(bmt,
                       times=times,
                       time="time",
                       entrytime="entrytime",
                       cause="cause")
## non-parametric model
outnp <- comp.risk(Event(time,cause)~tcell+platelet+const(age),
                   data=bmtw,
                   cause=1,
                   fix.gamma=1,
                   gamma=0,
                   cens.weights=bmtw$cw,
                   weights=bmtw$weights,
                   times=times,
                   n.sim=0)
par(mfrow=c(2,2))
plot(outnp)
```

```{r}
outnp <- comp.risk(Event(time,cause)~tcell+platelet,
                   data=bmtw,
                   cause=1,
                   cens.weights=bmtw$cw,
                   weights=bmtw$weights,
                   times=times,
                   n.sim=0)
par(mfrow=c(2,2))
plot(outnp)
```

```{r}
## semiparametric model
out <- comp.risk(Event(time,cause)~const(tcell)+const(platelet),
                 data=bmtw,
                 cause=1,
                 cens.weights=bmtw$cw,
                 weights=bmtw$weights,
                 times=times,
                 n.sim=0)
summary(out)
```
