```{r}
library(lubridate)
library(survival)
library(survminer)
library(ggplot2)
library(dplyr)
library(tidycmprsk)
library(tidyr)
library(ggsurvfit)
library(cmprsk)
library(readr)
library(data.table)
library(ggpubr)
library(survRM2)
```

```{r}
# Standardize values for publication font sizes and color schemes.
pubFontSize = 18
pValSize = 8
pubWidth = 8
pubHeight = 6
pubColorScheme = "Set1"
```

```{r}
# Load the AaveV2 Ethereum transaction data and filter out transactions after October 1, 2022 since 
# this is the data we used in the original paper

transactions <- read_rds("/data/IDEA_DeFi_Research/Data/Lending_Protocols/Aave/V2/Mainnet/transactions.rds")
coinTypes <- read_csv("/data/IDEA_DeFi_Research/Data/Coin_Info/stablecoins.csv")
# Run the files to make the functions that create the survival data:
source(".././Survival_Data_Creation/createSurvData.R")
source("./createCRDataTable.R")
source("./createSurvPlotCR.R")

tFinal <- as_datetime(ymd("2022-10-01"))

transactions <- transactions %>%
  filter(timestamp <= tFinal) %>%
  mutate(coinType = case_when(reserve %in% coinTypes$symbol ~ "Stable",
                              TRUE ~ "Non-Stable"))

## Helper functions
not_all_na <- function(x) any(!is.na(x))
`%notin%` <- Negate(`%in%`)
select <- dplyr::select
mutate <- dplyr::mutate
rename <- dplyr::rename

```

```{r}
indexEventSet <- c("borrow")
outcomeEventSet <- c("repay", "liquidation")
transactions <- transactions %>%
  mutate(reserve = case_when(type == "liquidation" ~ principalReserve,
                             TRUE ~ reserve)) %>%
  mutate()
subjects <- c("user",
              "reserve")
indexCovariates <- c("coinType")
outcomeCovariates <- c("type")
observationPeriod <- c(0, tFinal)
  
borrowToOutcome <- createSurvData(indexEventSet, outcomeEventSet, transactions, subjects, observationPeriod, indexCovariates, outcomeCovariates)


borrowToOutcome <- borrowToOutcome %>%
  mutate(endpoint = as.factor(case_when(status == 0 ~ "censor",
                           TRUE ~ type))) %>%
  filter(timeDiff != 0) %>%
  mutate(istate = "borrow") %>%
  select(id = indexID,
         time = timeDiff,
         endpoint,
         istate,
         coinType)

smallSet <- borrowToOutcome %>%
  slice_sample(prop = 1) %>%
  mutate(cause = as.numeric(endpoint), time = time/86400) %>%
  drop_na()

crDataTable <- createCRDataTable(smallSet, "coinType")

cumulativeIncFunction <- tidycmprsk::cuminc(Surv(time, endpoint) ~ coinType, data = smallSet) 

strataLabels <- crDataTable %>%
  select(Strata, Percentage_Strata) %>%
  distinct()

outcomeLabels <- crDataTable %>%
  select(Outcome, Percentage_Outcome) %>%
  distinct()

strataLegendLabels = paste0(strataLabels$Strata, " (", format(round(strataLabels$Percentage_Strata, 2)), "%)")
outcomeLegendLabels = paste0(outcomeLabels$Outcome, " (", format(round(outcomeLabels$Percentage_Outcome, 2)), "%)")


createSurvPlotCR(smallSet,
                   "coinType",
                   "How Does Coin Type Affect Repayment time?",
                   "Days",
                   "Cumulative Incidence",
                   strataLegendLabels,
                   outcomeLegendLabels,
                   c(.8, .5)
                   )

plot <- cumulativeIncFunction %>% 
  ggcuminc(outcome = c("repay", "liquidation")) + 
  labs(x = "Days") + 
  add_confidence_interval() + 
  ggtitle(label = "How Does Coin Type Affect Repayment time?") + 
  scale_x_continuous(breaks = seq(0, 650, by = 100)) + 
  theme(legend.position = c(.75, .5)) + 
  scale_fill_hue(name = "Coin Type", labels = strataLegendLabels) +
  scale_linetype(name = 'Outcome', labels = outcomeLegendLabels) +
  guides(color = "none")

plot

# Print the plot to a pdf:
image=ggpubr::ggpar(plot,
              font.legend = list(size = pubFontSize),
              font.xtickslab = list(size = pubFontSize),
              font.ytickslab = list(size = pubFontSize),
              font.x = list(size = pubFontSize),
              font.y = list(size = pubFontSize),
              font.subtitle = list(size = pubFontSize),
              font.title = list(size = pubFontSize),
              palette = pubColorScheme)

image
saveRDS(plot, file = "./Competing_Risks_Figures/borrowToRepayCoinTypePlot.rds")
ggsave(file="./Competing_Risks_Figures/borrowToRepayCoinType.pdf", plot, width=pubWidth, height=pubHeight)
```